#+TITLE: Solarized Color Scheme Setup
#+AUTHOR: wanglifeng
#+OPTIONS: H:4 ^:nil
#+LATEX_CLASS: latex-doc
#+PAGE_TAGS: solarized
#+PAGE_CATETORIES: sysadmin
#+PAGE_LAYOUT: post

#+HTML: <!--abstract-begin-->
solarized是一种非常流行的配色方案，适用于常见的编辑器，如vim, emacs, 及常见仿真终端。本文纪录iterm2, gnome-terminal, guake, SecureCRT, Tmux,  vim编辑器solarized的配置方法。
#+HTML: <!--abstract-end-->

* iTerm2

下载 [[https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized][iterm2-colors-solarized]] ，此处采用dark主题。

Open iTerm2, open Preferences, click on the "Profiles" (formerly Addresses, formerly Bookmarks) icon in the preferences toolbar, then select the "colors" tab. Click on the "load presets" and select "import...". Select the Solarized Light or Dark theme file.

You have now loaded the Solarized color presets into iTerm 2, but haven't yet applied them. To apply them, simply select an existing profile from the profile list window on the left, or create a new profile. Then select the Solarized Dark or Solarized Light preset from the "Load Presets" drop down.

* Gnome-terminal

You need the dconf command (if you run a recent Gnome version).

#+BEGIN_SRC sh
sudo apt-get install dconf-cli
cd /opt/git
git clone git@github.com:Anthony25/gnome-terminal-colors-solarized.git
cd gnome-terminal-colors-solarized
./install.sh
#+END_SRC

* Guake

#+BEGIN_SRC sh
cd /opt/git
git clone git@github.com:coolwanglu/guake-colors-solarized.git
cd guake-colors-solarized
./set_dark solarized
#+END_SRC

* vim

in vimrc:
#+BEGIN_SRC vim
Plugin 'altercation/vim-colors-solarized'
set background=dark
colorscheme solarized
#+END_SRC

* dircolors-solarized

** Linux
#+BEGIN_SRC sh
cd /opt/git
git clone git@github.com:seebi/dircolors-solarized.git
cp /opt/git/dircolors-solarized/dircolors.256dark ~/.dircolors.256dark
cat >> ~/.zshrc << EOF
eval `dircolors ~/.dircolors.256dark`
EOF
#+END_SRC

** MAC

#+BEGIN_SRC sh
cd /opt/git
git clone git@github.com:seebi/dircolors-solarized.git
cp /opt/git/dircolors-solarized/dircolors.256dark ~/.dircolors.256dark
brew install coreutils
cat >> ~/.zshrc << EOF
eval `gdircolors ~/.dircolors.256dark`
alias ls='gls --color=auto'
EOF
#+END_SRC

* Tmux

#+BEGIN_EXAMPLE
set -g default-terminal "screen-256color"
set -g status-left "#[fg=green]s#S:w#I.p#P#[default]"

#### COLOUR (Solarized dark
# default statusbar colors
set-option -g status-bg black #base02
set-option -g status-fg yellow #yellow
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg brightblue #base0
set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg brightred #orange
set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg black #base02
set-option -g pane-active-border-fg brightgreen #base01

# message text
set-option -g message-bg black #base02
set-option -g message-fg brightred #orange

# pane number display
set-option -g display-panes-active-colour blue #blue
set-option -g display-panes-colour brightred #orange

# clock
set-window-option -g clock-mode-colour green #green

#+END_EXAMPLE

* SecureCRT

- [[https://raw.githubusercontent.com/wanglf/dotfiles/master/securecrt/Global.ini][Global.ini]]
- [[https://raw.githubusercontent.com/wanglf/dotfiles/master/securecrt/Color%20Schemes.ini][Color Schemes.ini]]

* Terminal type

#+BEGIN_SRC sh
export TERM=xterm-256color        # for common 256 color terminals (e.g. gnome-terminal)
export TERM=screen-256color       # for a tmux -2 session (also for screen)
export TERM=rxvt-unicode-256color # for a colorful rxvt unicode session
#+END_SRC

* Screenshot
** iTerm2
#+BEGIN_CENTER
#+ATTR_LATEX: :float t :placement [H] :width 6cm
file:fig/iterm2_solarized.png
#+END_CENTER

** dircolor
#+BEGIN_CENTER
#+ATTR_LATEX: :float t :placement [H] :width 6cm
file:fig/dircolor_solarized.png
#+END_CENTER
