#+TITLE: 软件随想录卷2-书摘
#+AUTHOR: wanglifeng
#+OPTIONS: H:4 ^:nil
#+LATEX_CLASS: latex-doc
#+PAGE_TAGS: books
#+PAGE_CATETORIES: books
#+PAGE_LAYOUT: post

#+HTML: <!--abstract-begin-->
Joel Spolsky是世界上最有影响力的程序员之一，被誉为“程序员部落酋长”，开设的个人博客"joel on software"(www.joelonsoftware.com)深受全世界程序员的欢迎。2000年与人联合创办Fog Creek软件公司并经营至今；2008年创办全球最大软件技术问答服务网站stackoverflow并任CEO；2011年被创业孵化器TechStarts聘为创业导师。《软件随想录》收录的是Joel发表在网志上的一部分文章。
#+HTML: <!--abstract-end-->

* 为什么做一个内部程序员就糟透了

- 你永远无法用正确的方法做事，你总是被迫用最保险的方法做事
- 一旦你的程序可以用了，你就不得不停止开发。只要核心功能具备了，主要问题解决了，再投资没有商业理由
- 如果你在专业的软件公司或互联网公司中编程，你的工作与公司的主营业务直接相关，是能够为公司直接带来收入的。这至少意味着管理层会想到你。

内部使用的软件很少需要雇用巨星来开发。这就是为什么最令人满意的职业生涯(如果你是程序员)往往是在真正的软件公司里，而不是在银行里担任IT人员。

* 指针与递归

大学计算机系的课程里有两个传统的知识点，但许多人从来没有真正搞懂过，那就是指针(pointer)和递归(recursion)。

* 赢家通吃

眼下的软件市场有点"赢家通吃"(winner-take-all)的味道。除了苹果公司，没有其他人能在MP3播放器市场赚到钱。除了微软公司，没有其他人能在电子表格和文字处理器市场上赚到钱。

* 程序员的生产效率

最好的工作条件 -> 最好的程序员 -> 最好的软件 -> 利润

* 关于软件创业

- 如果你说不清楚你的软件解决了什么*棘手*的问题，就不要去开软件公司。
- 不要独自一人创办公司
- 一开始不要抱太高期望

* 五个为什么

  我们机房的连接中断了

- 为什么? 我们交换机里的网线接口好像不工作了
- 为什么? 与网络运营中心交换意见后，我们判断这个问题很可能是由于网速/双工模式不匹配造成的。
- 为什么? 交换机网口被设置成自动协商，而没有手动设置在一个固定档。
- 为什么? 许多年前，我们就清楚地知道有可能发生此类故障。但是，我们始终没有写出一份书面的技术说明文档，用于指导和检查交换机在生产环境中的配置。
- 为什么？我们总是很狭隘地看待技术说明文档，觉得只有在找不到系统管理员的情况下才需要去看它，或者觉得只有运营团队中那些不负责系统管理的成员才需要去看它。我们没有认识到应该把它作为技术操作的标准和确认清单。

* 给计算机系学生的建议

- 毕业前练好写作
- 毕业前学好C语言
- 毕业前学好微观经济学
- 不要因为枯燥就不选修非计算机专业的课程
- 选修带有大量编程实践的课程
- 别担心所有工作都被印度人抢走
- 找一份好的时期实习工作
